import { ConvexError } from 'convex/values';

export type ErrorCode =
  | 'UNAUTHENTICATED'
  | 'USER_NOT_FOUND'
  | 'MEMBERSHIP_NOT_FOUND'
  | 'CANNOT_REMOVE_ORGANISATION_CREATOR'
  | 'NO_ACTIVE_ORGANISATION'
  | 'NO_EMAIL'
  | 'NO_MEMBERSHIPS_FOUND'
  | 'NO_MEMBERSHIPS_WITH_USERS_FOUND'
  | 'STORAGE_NOT_FOUND'
  | 'CANNOT_DEMOTE_ORGANISATION_CREATOR'
  | 'ORGANISATION_NOT_FOUND'
  | 'ORGANISATION_ALREADY_EXISTS'
  | 'INVITATION_NOT_FOUND'
  | 'INVITEE_EMAIL_MISMATCH'
  | 'NOT_ADMIN_OF_ORGANISATION'
  | 'CANNOT_INVITE_SELF'
  | 'INVITEE_ALREADY_MEMBER'
  | 'INVITATION_ALREADY_EXISTS'
  | 'NO_MEMBERSHIPS_WITH_ORGANISATION_FOUND'
  | 'ASSESSMENT_NOT_FOUND'
  | 'FRAMEWORK_NOT_FOUND'
  | 'USER_ASSESSMENT_NOT_FOUND'
  | 'NOT_USER_ASSESSMENT_USER'
  | 'SECTION_NOT_FOUND'
  | 'DOMAIN_NOT_FOUND'
  | 'QUESTION_NOT_FOUND'
  | 'ACTION_NOT_FOUND';

export function createConvexError(code: ErrorCode) {
  return new ConvexError(code);
}
